# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WelsonAppLoader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15WelsonAppLoader.proto\"\x1d\n\nAppRequest\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\"#\n\x0b\x41ppResponse\x12\x14\n\x0cresponseText\x18\x01 \x01(\t25\n\x0fWelsonAppLoader\x12\"\n\x03Run\x12\x0b.AppRequest\x1a\x0c.AppResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WelsonAppLoader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_APPREQUEST']._serialized_start=25
  _globals['_APPREQUEST']._serialized_end=54
  _globals['_APPRESPONSE']._serialized_start=56
  _globals['_APPRESPONSE']._serialized_end=91
  _globals['_WELSONAPPLOADER']._serialized_start=93
  _globals['_WELSONAPPLOADER']._serialized_end=146
# @@protoc_insertion_point(module_scope)
